title: Stackbit Startup Theme
baseURL: /
params:
  layout_type: full-width
  style: classic
  palette: gray
  mode: light
  base_font: serif
  header:
    title: Startup
    logo: images/logo.svg
    logo_alt: YourGoal logo
    has_primary_nav: false
    has_secondary_nav: true
    secondary_nav_links:
      - label: About
        url: /about
        style: link
      - label: FAQ
        url: /faq
        style: link
      - label: Blog
        url: /blog
        style: link
    has_anncmnt: true
    anncmnt_has_close: true
    anncmnt_content: |
      We use cookies to ensure that you get the best experience.

      \[Learn More]\(/)
    anncmnt_align: left
  footer:
    logo_alt: YourGoal logo
    has_primary_nav: true
    primary_nav_title: Company
    primary_nav_links:
      - label: About
        url: /about
        style: link
      - label: FAQ
        url: /faq
        style: link
      - label: Style Guide
        url: /style-guide
        style: link
    has_secondary_nav: true
    secondary_nav_title: Blog
    secondary_nav_links:
      - label: News
        url: /blog/category/news
        style: link
      - label: Tips
        url: /blog/category/tips
        style: link
      - label: Use Cases
        url: /blog/category/use-cases
        style: link
    has_tertiary_nav: true
    tertiary_nav_title: Legal
    tertiary_nav_links:
      - label: Terms & Conditions
        url: /terms-conditions
        style: link
      - label: Privacy Policy
        url: /privacy-policy
        style: link
    has_social: true
    social_links:
      - label: Twitter
        url: 'https://twitter.com/'
        style: link
        has_icon: true
        icon: twitter
        icon_position: center
        new_window: true
      - label: Instagram
        url: 'https://instagram.com/neogalactic'
        style: link
        has_icon: true
        icon: instagram
        icon_position: center
        new_window: true
      - label: Facebook
        url: 'https://facebook.com/neogalacticexploration'
        style: link
        has_icon: true
        icon: facebook
        icon_position: center
        new_window: true
      - label: YouTube
        url: 'https://www.youtube.com/'
        style: link
        has_icon: true
        icon: youtube
        icon_position: center
        new_window: true
      - label: GitHub
        url: 'https://github.com/neogalactic'
        style: link
        has_icon: true
        icon: github
        icon_position: center
        new_window: true
    content: '&copy; 2021 NEO GALACTIC. ALL RIGHTS RESERVED.'
  domain: 'https://alternative-d45dc.netlify.app'
  favicon: images/favicon.png
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
